config/routes.rb
Todo::Application.routes.draw do

  devise_for :users

  resources :lists do
    resources :items do
      collection do
        delete 'destroy_multiple'
      end
    end
  end

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :users
      resources :lists
      resources :items
    end
  end

  root to: 'welcome#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :user
end

app/controllers/api/v1/lists_controller.rb
class API::V1::ListsController < ApplicationController

  respond_to :html, :js, :json

  def index
    @lists = List.all
    respond_to do |format|
      format.json { render :json => @lists }
    end
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items
    authorize @i
    respond_to do |format|
      format.json { render :json => @list }
    end
  end

  def create
    @list = List.new(list_params)
    respond_to do |format|
    if @list.save
      format.json { render json: @list, status: :created }
    else
      format.json { render json: @list.errors, status: :unprocessable_entity }
    end
  end
  end

  def update
    @list = policy_scope(List.find(params[:id]))
    respond_to do |format|
      if @list.update_attributes(list_params)
        format.json { head :no_content, status: :ok }
      else
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list = List.find(params[:id])
    respond_to do |format|
      if @list.destroy
        format.json { head :no_content, status: :ok }
      else
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def list_params
      params.require(:list).permit(:title, :viewable, :open)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :html, :js

  def index
    @list = List.all
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List was saved."
      redirect_to @list
    else
      flash[:error] = "There was an error creating your list."
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      flash[:notice] = "List was updated."
      redirect_to @list
    else
      flash[:error] = "There was an error updating your list."
      redirect_to @list
    end
  end

  private
    def list_params
      params.require(:list).permit(:title)
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list, html: {class: 'form-horizontal'} do |f| %>

    <label>Title</label>
    <div class="control-group">
      <div class="controls">
        <p><%= f.text_field :title %></p>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.submit "Add List", class: 'btn' %>
      </div>
    </div>

<% end %>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/new.html.erb
<h1>New Todo List</h1>

<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<table class="table table-striped">
  <tr>
    <td>Description</td>
    <td>Days Left</td>
    <td>Completed</td>
  </tr>
<%= form_tag destroy_multiple_list_items_path(@list, @item), method: :delete do %>
  <% @items.each do |item| %>
    <tr>
      <td><%= item.description %></td>
      <td><%= distance_of_time_in_words(7.days.ago - item.created_at) %></td>
      <td><%= check_box_tag "completed[item_ids][]", item.id %></td>
    </tr>
  <% end %>
</table>
<%= submit_tag "Mark as Complete" %>
<% end %>

<%= link_to "New Todo Item", new_list_item_path(@list, @item), class: 'btn btn-large' %>